version: '3'
services:

  api:
    container_name: api
    image: nag0124/api
    expose:
      - 8080
    ports:
      - 8080:8080

  web:
    container_name: web
    image: nag0124/web
    ports:
      - 80:80
    depends_on:
      - api
