FROM node:18.17.1 as web
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=web /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
