version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: second_hand
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 6379:6379
